#pragma once

#include "core/collect/platform_schema.h"

namespace silicore::collect {

PlatformConfig build_platform_about_me();
PlatformConfig build_platform_academia_edu();
PlatformConfig build_platform_archive_org();
PlatformConfig build_platform_artstation();
PlatformConfig build_platform_asciinema();
PlatformConfig build_platform_ask_fedora();
PlatformConfig build_platform_atcoder();
PlatformConfig build_platform_bandcamp();
PlatformConfig build_platform_behance();
PlatformConfig build_platform_bitbucket();
PlatformConfig build_platform_blogger();
PlatformConfig build_platform_bugcrowd();
PlatformConfig build_platform_buymeacoffee();
PlatformConfig build_platform_codeberg();
PlatformConfig build_platform_codeforces();
PlatformConfig build_platform_codepen();
PlatformConfig build_platform_coderwall();
PlatformConfig build_platform_codewars();
PlatformConfig build_platform_credly();
PlatformConfig build_platform_crowdin();
PlatformConfig build_platform_cssbattle();
PlatformConfig build_platform_cyberdefenders();
PlatformConfig build_platform_dailymotion();
PlatformConfig build_platform_dev_to();
PlatformConfig build_platform_deviantart();
PlatformConfig build_platform_discogs();
PlatformConfig build_platform_discord();
PlatformConfig build_platform_disqus();
PlatformConfig build_platform_dockerhub();
PlatformConfig build_platform_dribbble();
PlatformConfig build_platform_eyeem();
PlatformConfig build_platform_facebook();
PlatformConfig build_platform_flickr();
PlatformConfig build_platform_github();
PlatformConfig build_platform_gitlab();
PlatformConfig build_platform_hackerone();
PlatformConfig build_platform_hackerrank();
PlatformConfig build_platform_instagram();
PlatformConfig build_platform_kaggle();
PlatformConfig build_platform_keybase();
PlatformConfig build_platform_leetcode();
PlatformConfig build_platform_linkedin();
PlatformConfig build_platform_mastodon();
PlatformConfig build_platform_medium();
PlatformConfig build_platform_npm();
PlatformConfig build_platform_pastebin();
PlatformConfig build_platform_patreon();
PlatformConfig build_platform_pinterest();
PlatformConfig build_platform_producthunt();
PlatformConfig build_platform_pypi();
PlatformConfig build_platform_quora();
PlatformConfig build_platform_reddit();
PlatformConfig build_platform_replit();
PlatformConfig build_platform_roblox();
PlatformConfig build_platform_snapchat();
PlatformConfig build_platform_soundcloud();
PlatformConfig build_platform_sourceforge();
PlatformConfig build_platform_spotify();
PlatformConfig build_platform_stackoverflow();
PlatformConfig build_platform_steamcommunity();
PlatformConfig build_platform_telegram();
PlatformConfig build_platform_threads();
PlatformConfig build_platform_tiktok();
PlatformConfig build_platform_tryhackme();
PlatformConfig build_platform_twitch();
PlatformConfig build_platform_twitter_x();
PlatformConfig build_platform_unsplash();
PlatformConfig build_platform_vimeo();
PlatformConfig build_platform_wordpress();
PlatformConfig build_platform_youtube();

} // namespace silicore::collect
