set(SILICORE_PLATFORM_SOURCES
  src/platforms/platform_about_me.cpp
  src/platforms/platform_academia_edu.cpp
  src/platforms/platform_archive_org.cpp
  src/platforms/platform_artstation.cpp
  src/platforms/platform_asciinema.cpp
  src/platforms/platform_ask_fedora.cpp
  src/platforms/platform_atcoder.cpp
  src/platforms/platform_bandcamp.cpp
  src/platforms/platform_behance.cpp
  src/platforms/platform_bitbucket.cpp
  src/platforms/platform_blogger.cpp
  src/platforms/platform_bugcrowd.cpp
  src/platforms/platform_buymeacoffee.cpp
  src/platforms/platform_codeberg.cpp
  src/platforms/platform_codeforces.cpp
  src/platforms/platform_codepen.cpp
  src/platforms/platform_coderwall.cpp
  src/platforms/platform_codewars.cpp
  src/platforms/platform_credly.cpp
  src/platforms/platform_crowdin.cpp
  src/platforms/platform_cssbattle.cpp
  src/platforms/platform_cyberdefenders.cpp
  src/platforms/platform_dailymotion.cpp
  src/platforms/platform_dev_to.cpp
  src/platforms/platform_deviantart.cpp
  src/platforms/platform_discogs.cpp
  src/platforms/platform_discord.cpp
  src/platforms/platform_disqus.cpp
  src/platforms/platform_dockerhub.cpp
  src/platforms/platform_dribbble.cpp
  src/platforms/platform_eyeem.cpp
  src/platforms/platform_facebook.cpp
  src/platforms/platform_flickr.cpp
  src/platforms/platform_github.cpp
  src/platforms/platform_gitlab.cpp
  src/platforms/platform_hackerone.cpp
  src/platforms/platform_hackerrank.cpp
  src/platforms/platform_instagram.cpp
  src/platforms/platform_kaggle.cpp
  src/platforms/platform_keybase.cpp
  src/platforms/platform_leetcode.cpp
  src/platforms/platform_linkedin.cpp
  src/platforms/platform_mastodon.cpp
  src/platforms/platform_medium.cpp
  src/platforms/platform_npm.cpp
  src/platforms/platform_pastebin.cpp
  src/platforms/platform_patreon.cpp
  src/platforms/platform_pinterest.cpp
  src/platforms/platform_producthunt.cpp
  src/platforms/platform_pypi.cpp
  src/platforms/platform_quora.cpp
  src/platforms/platform_reddit.cpp
  src/platforms/platform_replit.cpp
  src/platforms/platform_roblox.cpp
  src/platforms/platform_snapchat.cpp
  src/platforms/platform_soundcloud.cpp
  src/platforms/platform_sourceforge.cpp
  src/platforms/platform_spotify.cpp
  src/platforms/platform_stackoverflow.cpp
  src/platforms/platform_steamcommunity.cpp
  src/platforms/platform_telegram.cpp
  src/platforms/platform_threads.cpp
  src/platforms/platform_tiktok.cpp
  src/platforms/platform_tryhackme.cpp
  src/platforms/platform_twitch.cpp
  src/platforms/platform_twitter_x.cpp
  src/platforms/platform_unsplash.cpp
  src/platforms/platform_vimeo.cpp
  src/platforms/platform_wordpress.cpp
  src/platforms/platform_youtube.cpp
)
